<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hqr-aabdulkarem" failures="1" tests="4" name="AuditorRegistration.AuditorRegistration" time="10.331" errors="0" timestamp="2022-03-21T13:18:50 AST" skipped="2">
  <testcase classname="AuditorRegistration.AuditorRegistration" name="positiveOrganizationInfoTest" time="10.064"/>
  <system-out/>
  <testcase classname="AuditorRegistration.AuditorRegistration" name="acknowledgmentTest" time="0.267">
    <failure message="The following asserts failed:
	expected [Mar 21, 2022] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Mar 21, 2022] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at AuditorRegistration.AuditorRegistration.acknowledgmentTest(AuditorRegistration.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Application.App.runTest(App.java:133)
at Application.App.main(App.java:146)
]]>
    </failure>
  </testcase> <!-- acknowledgmentTest -->
  <system-out/>
  <testcase classname="AuditorRegistration.AuditorRegistration" name="negativeOrganizationInfoTest">
    <skipped/>
  </testcase> <!-- negativeOrganizationInfoTest -->
  <system-out/>
  <testcase classname="AuditorRegistration.AuditorRegistration" name="positivePasswordTest">
    <skipped/>
  </testcase> <!-- positivePasswordTest -->
  <system-out/>
</testsuite> <!-- AuditorRegistration.AuditorRegistration -->
